# Generated by Django 4.2 on 2024-03-22 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_orderdetail'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderdetail',
            table='tbl_order_detail',
        ),
    ]
